import { test, expect } from '@playwright/test';
test('test',async({ page }) => {
  await page.goto('https://demoqa.com/');
  await page.getByText('Elements').click();
  await page.getByText('Text Box').click();
   await page.locator('[id="userName"]').fill('vignesh k');
  await page.locator('[id="userEmail"]').fill('vigneshk@gmail.com');
  await page.locator('[id="currentAddress"]').fill('velacherry chennai');
   await page.locator('[id="permanentAddress"]').fill('T.nagar chennai');
  await page.getByText('Submit').click(); 
//   await page.getByText('Check Box').click(); 
//   await page.getByText('Home').click(); 
//   await page.getByText('Radio Button').click(); 
//   await page.getByText('Yes').click();
//   await page.getByText('Web Tables').click();
//   await page.locator('[id="delete-record-1"]').click();
//   await page.getByText('Buttons').click();
//   await page.getByText('Double Click Me').dblclick();
//   //await page.getByText('Links').click();
//   await page.getByText('Broken Links - Images').click();
//  // await page.getByText('Click Here for Valid Link').click();
//  await page.getByText('Upload and Download').click();
//  //await page.locator('[id="uploadFile"]').click();
//  await page.getByText('Dynamic Properties').click();
//   await page.getByText('Will enable 5 seconds').dblclick();
//  await page.getByText('Forms').click();
//   await page.getByText('Practice Form').click();
// await page.locator('#firstName').fill('priya');
//  await page.locator('#lastName').fill('k');
//  await page.locator('#userEmail').fill('priyak@gmail.com');
//   await page.getByText('Female').click();
//   await page.locator('#userNumber').fill('9785236548');
//    await page.locator('#dateOfBirthInput').fill('31 May 2023');
//   // await page.getByText('May').click();
//     //await page.getByText('2023').click();
//      //await page.getByText('20').click();
//      await page.locator('#dateOfBirthInput').fill('31 May 2023');
//     await page.locator('[id="subjectsContainer"]').fill('test');
//      await page.getByText('Reading').click();
//       await page.locator('#currentAddress').fill('kv nagar chennai');
//       await page.getByText('Select State').click();
//        await page.getByText('Uttar Pradesh').click();
//        await page.getByText('Agra').click();
//       await page.getByText('Submit').click();
//     await page.getByText('Alerts, Frame & Windows').click();
//   await page.getByText('Modal Dialogs').click();
//   await page.getByText('Small modal').click();
//   await page.locator('#closeSmallModal').click();
//    await page.getByText('Widgets').click();
//     await page.getByText('Progress Bar').click();
//    await page.getByText('Start').click();
//   await page.locator('[id="demo-tab-origin"]').click();
//   await page.getByText('Interactions').click();
//  await page.getByText('Book Store Application').click();
//   await page.getByText('Speaking JavaScript').click();
//  await page.locator('[id="addNewRecordButton"]').click();


});

